### ISSUE TITLE
  PARSE ERRS: 53       Exception in thread "main" java.lang.OutOfMemoryError: Java heap space      5:52 执行 java -jar target/pysonar-2.1.2.jar /usr/lib/python2.7 ./html 报的错的

### ISSUE THREAD

**Issue by harryheng** [yinwang0/pysonar2#109]
PARSE ERRS: 53       Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

5:52
执行 java -jar target/pysonar-2.1.2.jar /usr/lib/python2.7 ./html 报的错的

**Comment by yummic** [comment]
**加大内存。**

如果系统内存不够，就不要跑这个目录了，里面的文件太多了，可以单独跑一个小目录。
