### ISSUE TITLE
王垠,不要离开,我们需要你

### ISSUE THREAD

**Issue by tm-roamer** [yinwang0/pysonar2#53]
十分抱歉用这样十分唐突的方式联系找你, 我实在找不到你,我今天(2014年12月10)刚看到你的<程序员的心理疾病>文章,如获至宝,看见你的文章我如梦初醒,似乎看清楚了些什么,找到你的新浪博客http://blog.sina.com.cn/yinwang0,但是已经关闭了, 我心痛不已, 为什么一个针砭时弊的优秀的人放弃抵抗, 我想用轻微的语言留住你,不要离开我们.
我87年生人, 是个大专生, 没有华丽的背景, 更没有多么高的天赋, 像我一样的代码民工在北上广有很多, 脑袋笨笨想挣点钱,攒点钱, 但是我不傻, 我知道什么样的人是好人, 你是那个好人, 如果每个高手都归隐山林, 留下的那份责任谁来承担呢,大家都说能力越大,责任越大, 请不要轻易放弃我们, 请拿起你的学识振臂高呼吧,
改变需要时间,请不要失去耐心,推翻旧的陋习需要反抗,请带领我们走出沼泽.

如果司马迁放弃了就没有史记了;
如果甘地放弃了印度会变成什么样子;
如果马丁路德金放弃了呢?
如果超人,蝙蝠侠,蜘蛛侠,超级英雄放弃抵抗了呢?

当我看到你的文章,我瞬间就心跳加速了高兴不已, 你看见了, 看见了别人看不到的地方,你是多么宝贵,
你是多么幸运可以去推翻旧的环境,去粉刷新的房子,如果说我们生下来并不属于自己,生下来就是为了改变世界,让世界更美好,去帮助别人,让自己和别人变的更好. 如果你认同, 请原谅那些伤害你的人, 哪怕会再次受伤, 也请你再一次带领我们, 去帮助我们认识真实的世界, 我们总会明白你的苦心, 那些先慢慢醒来的人跟随你的脚步去唤醒起更多的人.

最后恳请你不要禁声,世界已经很丑陋了,我们太需要你这样的人,哪怕一张黑纸上只有一个白点, 哪怕白点很小,我们也是有希望去对抗黑暗和丑陋的. 

我叫田明 邮箱tm165822@163.com  (请原谅我的唐突给你带来的不便)

**Comment by settinghead** [comment]
+1. 我是一个在国外软件公司上班的程序员，很赞同你关于程序员沟通问题上的看法。加油，希望看到你不断前进。

**Comment by nightire** [comment]
He doesn't need followers, but wants you to have your own minds.

**Comment by mauersu** [comment]
@nightire 说得好 @tm-roamer 技术社区谈技术嘛

**Comment by mauersu** [comment]
<程序员的心理疾病>这篇文章感触颇深，反思了自己做程序员期间种种内心想法，以之为耻，以后必引以为戒。
软件源于技术，技术源自公司，公司服务于资本市场，资本市场只在乎钱生钱，这是我从另一个角度对编程的认识。
