### ISSUE TITLE
I just want to contact you.

### ISSUE THREAD

**Issue by AdaJass** [yinwang0/pysonar2#58]
我是个人工智能爱好者，这一生都打算用于实现强人工智能，不知道你对此感不感兴趣。目前我还是刚刚大学毕业不久，或许没你聪明，但刚看你文章发现对研究的热爱和态度是和你一样的。如果一切都好的话，我会在未来2年内组建自己的公司和团队，然后搞AI。其实对于我们这样的人，缺的应该就是一个环境，而这个环境估计只能自己造。
  在公司和学校都不可能真正自由，在学校被各种学业束缚；在公司用的是别人的钱，被经济束缚。但是，难道自己建公司就不被经济束缚了？但总要自由好多吧，这世上真正自由的条件大概就是需要经济自由吧。不知道你对此有没有兴趣。公司 和 AI。

**Comment by jack999123** [comment]
你有什么想法，说来听听。
你准备在哪创业

**Comment by AdaJass** [comment]
我email: 1252348575@qq.com 你的呢？
