### ISSUE TITLE
error with unexpected ast node

### ISSUE THREAD

**Issue by jkitchin** [yinwang0/pysonar2#60]
21:06 $ java -jar target/pysonar-2.0-SNAPSHOT.jar ~/anaconda3/lib/python3.5 .html
copied models to: /private/var/folders/5q/lllv2yf95hg_n6h6kjttbmdw0000gn/T/pysonar2/models.64a3d6b9-89de-4fbc-a882-7edc10d7a0d6
AST cache is at: /private/var/folders/5q/lllv2yf95hg_n6h6kjttbmdw0000gn/T/pysonar2/ast_cache
started: python
started: python3
Loading and analyzing files
[Please report bug]: unexpected ast node: AsyncFunctionDef
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at org.yinwang.pysonar._.die(_.java:344)
	at org.yinwang.pysonar._.die(_.java:333)
	at org.yinwang.pysonar.Parser.convert(Parser.java:626)
	at org.yinwang.pysonar.Parser.convertListNode(Parser.java:680)
	at org.yinwang.pysonar.Parser.convertBlock(Parser.java:696)
	at org.yinwang.pysonar.Parser.convert(Parser.java:107)
	at org.yinwang.pysonar.Parser.parseFileInner(Parser.java:959)
	at org.yinwang.pysonar.Parser.parseFile(Parser.java:900)
	at org.yinwang.pysonar.AstCache.getAST(AstCache.java:99)
	at org.yinwang.pysonar.Analyzer.getAstForFile(Analyzer.java:378)
	at org.yinwang.pysonar.Analyzer.parseAndResolve(Analyzer.java:331)
	at org.yinwang.pysonar.Analyzer.loadFile(Analyzer.java:317)
	at org.yinwang.pysonar.Analyzer.loadFileRecursive(Analyzer.java:517)
	at org.yinwang.pysonar.Analyzer.loadFileRecursive(Analyzer.java:513)
	at org.yinwang.pysonar.Analyzer.analyze(Analyzer.java:97)
	at org.yinwang.pysonar.demos.Demo.start(Demo.java:47)
	at org.yinwang.pysonar.demos.Demo.main(Demo.java:172)

**Comment by yinwang0** [comment]
Hmm... something new added to Python3?

**Comment by jkitchin** [comment]
It looks like it: http://greentreesnakes.readthedocs.org/en/latest/nodes.html#async-and-await

**Comment by yinwang0** [comment]
Hello early adopter :) Have some time working on it now. Do you have an example of async and await in Python?

**Comment by yinwang0** [comment]
I pushed a new [branch](https://github.com/yinwang0/pysonar2/tree/issue-60) with the fix. Can you take a look if it works now?

**Comment by jkitchin** [comment]
Thanks! It works a bit better:

> java -jar target/pysonar-2.0-SNAPSHOT.jar ~/anaconda3/lib/python3.5 html-3 

ends with 

```
[WARNING] NameConstant contains unrecognized value: null, please report issue
illegal operator: MatMult
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at org.yinwang.pysonar.$.die($.java:344)
	at org.yinwang.pysonar.$.die($.java:333)
	at org.yinwang.pysonar.Parser.convertOp(Parser.java:842)
	at org.yinwang.pysonar.Parser.convert(Parser.java:166)
	at org.yinwang.pysonar.Parser.convert(Parser.java:515)
	at org.yinwang.pysonar.Parser.convertListNode(Parser.java:686)
	at org.yinwang.pysonar.Parser.convertBlock(Parser.java:702)
	at org.yinwang.pysonar.Parser.convert(Parser.java:325)
	at org.yinwang.pysonar.Parser.convertListNode(Parser.java:686)
	at org.yinwang.pysonar.Parser.convertBlock(Parser.java:702)
	at org.yinwang.pysonar.Parser.convert(Parser.java:107)
	at org.yinwang.pysonar.Parser.parseFileInner(Parser.java:965)
	at org.yinwang.pysonar.Parser.parseFile(Parser.java:910)
	at org.yinwang.pysonar.AstCache.getAST(AstCache.java:99)
	at org.yinwang.pysonar.Analyzer.getAstForFile(Analyzer.java:378)
	at org.yinwang.pysonar.Analyzer.parseAndResolve(Analyzer.java:331)
	at org.yinwang.pysonar.Analyzer.loadFile(Analyzer.java:317)
	at org.yinwang.pysonar.Analyzer.loadFileRecursive(Analyzer.java:517)
	at org.yinwang.pysonar.Analyzer.loadFileRecursive(Analyzer.java:513)
	at org.yinwang.pysonar.Analyzer.analyze(Analyzer.java:97)
	at org.yinwang.pysonar.demos.Demo.start(Demo.java:47)
	at org.yinwang.pysonar.demos.Demo.main(Demo.java:172)

```

MatMult is a new operator in Python 3.5 for matrix multiplication, e.g. A @ B. I believe it is __matmul__ in classes.

**Comment by yinwang0** [comment]
should be fixed now

**Comment by jkitchin** [comment]
It worked a long time this time (about 5 hours I guess), and sadly, just
gave me this:

java -jar target/pysonar-2.0-SNAPSHOT.jar ~/anaconda3/lib/python3.5 html-3



100% (11772 of 11772)   SPEED:     0/s   AVG SPEED:     1/s   ETA: 0:0:0


Finished loading files. 8510 functions were called.

Analyzing uncalled functions

  0% (    29 of 152465)   SPEED:     0/s   AVG SPEED:     1/s   ETA:
42:20:36       Exception in thread "main" java.lang.OutOfMemoryError: GC
overhead limit exceeded


Nothing was created.

Curiously, I tried to run it again on a single file, and it seems to have
output the right things.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by yinwang0** [comment]
That's strange. It usually won't take more than a few minutes for almost any project on github. How large is your code?

I have noticed some other changes in python 3.5 might have affected pysonar too. Like NameConstant seems to have some change that causes lots of warnings.

**Comment by jkitchin** [comment]
I ran it on the python3 lib directory. I did get tons of NameConstant null
errors.

On Wednesday, March 23, 2016, Yin Wang <notifications@github.com> wrote:

> That's strange. It usually won't take more than a few minutes for almost
> any project on github. How large is your code?
>
> I have noticed some other changes in python 3.5 might have affected
> pysonar too. Like NameConstant seems to have some change that causes lots
> of warnings.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yinwang0/pysonar2/issues/60#issuecomment-200606707>
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by yinwang0** [comment]
Just fixed those null's. Ran it on my old python lib repo and it does become terribly slow. I have no idea why...

**Comment by jkitchin** [comment]
It seems to work ok on small projects. and the nulls did seem to disappear. Thanks for the help!

**Comment by yinwang0** [comment]
I finished a run of cpython library from https://github.com/python/cpython. It took just about 10 mins. The stats shows that it needs about 1.55G of memory to do so, so may be you haven't given it enough memory?

Maybe you can try again, but shouldn't wait for more than 20 minutes for it to finish.


=================
started: python
started: python3
Loading and analyzing files
100% (1796 of 1796)   SPEED:     1/s   AVG SPEED:     6/s   ETA: 0:0:0   PARSE ERRS: 14       
Finished loading files. 3081 functions were called.
Analyzing uncalled functions
100% (41845 of 41845)   SPEED:   333/s   AVG SPEED:   144/s   ETA: 0:0:0   PARSE ERRS: 14       
---------------- analysis summary ----------------
- total time: 0:9:27
- modules loaded: 1768
- semantic problems: 1708
- failed to parse: 14
- number of definitions: 694302
- number of cross references: 819706
- number of references: 607884
- resolved names: 518941
- unresolved names: 64119
- name resolve rate:  89%
---------------- memory stats ----------------
- total collections: 116
- total collection time: 0:0:12
- total memory: 1.55G

Generating HTML
Adding xref links
 99% (691147 of 694302)   SPEED: 1379534/s   AVG SPEED: 1379534/s   ETA: 0:0:0   PARSE ERRS: 14       
Adding ref links
100% (1768 of 1768)   SPEED:   457/s   AVG SPEED:   301/s   ETA: 0:0:0   PARSE ERRS: 14       
Wrote 1768 files to /Users/u289/results/cpython
---------------- memory stats ----------------
- total collections: 162
- total collection time: 0:0:12
- total memory: 1.55G

Process finished with exit code 0

**Comment by jkitchin** [comment]
I doubt it was a lack of memory, I have 8 GB of RAM. I don't actually need the html for the whole distribution, I was just reporting what happened.I had tried to run in on my Anaconda installation. I don't know if that is unusually large.

**Comment by yinwang0** [comment]
I just found out what's Anaconda. It's a bunch of over 400 different python packages. The code is 18 times as big as cpython's standard lib. It's like loading a whole Linux distribution (like Ubuntu) into a C IDE. So no doubt you will run out of memory :) In the case of Anaconda you must use pysonar separately on each package instead running it on them all at once.

Thanks so much for providing feedback and information.

**Comment by jkitchin** [comment]
What I wanted to do with it is this: given a script, and line# and column #, tell me what kind of "thing" is at that point, so that you could run pydoc "indentifier" to access documentation about the "thing". So for example if I had something like:

`import numpy as np
a =np.array([6])
#stuff
print(a...
        ^
`
with a cursor on a, I would be able to run pydoc numpy.array 

does that make sense?

**Comment by yinwang0** [comment]
Yes you can do that. Parsing information from the demo's HTML output is not a good idea though. You may want to write some Java code and call the inferencer, and then get the data directly from the internal data structures. The demo code might be an example where to start. It's not well documented though ;)

So this issue is considered resolved. Thank you so much for providing feedback.
