### ISSUE TITLE
Generate call graph?

### ISSUE THREAD

**Issue by JesseAldridge** [yinwang0/pysonar2#64]
I'd like to generate a call graph of a python codebase via static analysis (like what https://github.com/gousiosg/java-callgraph does for Java code).  I think I might be able to use pysonar2 to do this.  Is this possible?  I'm not sure where I would need to hook into the code.

**Comment by yinwang0** [comment]
It's pretty easy to do by modifying the type inferencer. Most of the hard work is already done. But it's not still not straightforward.
