### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by hurryzeng** [yinwang0/pysonar2#69]
how about add support for unicode?

if a py file declares `#coding=utf-8`, 
then add a meta node in the header of related html file:
<code>
&lt;meta charset="utf-8"&gt;
</code>
or if pysonar2 does support unicode, plz tell me how....

thanks!

**Comment by yinwang0** [comment]
It already supports unicode declarations line #coding=utf-8. It just didn't put the <meta> tag in html. You can manually set it to unicode in the browser and should see results.

**Comment by hurryzeng** [comment]
i forced it to add the tag by modifying Demo.java to work around....
for my own code, only utf-8 will be used.

**Comment by yinwang0** [comment]
What browser do you use? My browser can display it correctly no matter the meta tag is there or not.
