### ISSUE TITLE
Use pysonar2 to implement some bug patterns? Like pylint..

### ISSUE THREAD

**Issue by GeekMin** [yinwang0/pysonar2#74]
Nobody has done that based on the Pysonar?
(Based on the more accurate type inference..?)
This thought(base on pysonar2 to generate python static analyzer tools built into daily code commit in jenkis..) is it sound?

**Comment by yinwang0** [comment]
It is totally possible to do so, but because of resource limitations, my role is just to provide the underlying technology. I'm not an integration vendor ;) I hope somebody else take the job of integration into CI tools etc.
