### ISSUE TITLE
How to get errors in Python code

### ISSUE THREAD

**Issue by ezhiksonic** [yinwang0/pysonar2#96]
Hello!

Is there a simple way to find errors in Python code using Pysonar2, for example this error
[Cannot apply binary operator ... to type ... and ...](https://github.com/yinwang0/pysonar2/blob/master/src/main/java/org/yinwang/pysonar/visitor/TypeInferencer.java#L136)
and how can I see if there is a parse error on a certain line?

When I generated html files, following the instructions, I found that it doesn't contain any information about errors in code.

**Comment by yinwang0** [comment]
You can use an option on the command line: -report

Notice this feature is not accurate and may generate false positives.
