### ISSUE TITLE
bug case in circular reference

### ISSUE THREAD

**Issue by steedfly** [yinwang0/pysonar2#99]
test1.py:
`class RequestFactory(object):

    def __init__(self):
        pass
    def get(self):
        return 1
    pass

from test2 import RequestFactory
print('in test1', RequestFactory().get())`

test2.py
`class RequestFactory(object):

    def __init__(self):
        pass
    def get(self):
        return 2
    pass

from test1 import RequestFactory`

then generated test1.py.html link of RequestFactory point to it self.

**Comment by yinwang0** [comment]
This is actually correct behavior. You can run the code your self, adding a similar print line on the bottom of test2.py.

If I run: python test2.py, I get:
    in test2 1
    in test1 1
    in test2 1

But if I run: python test1.py, I get:
    in test1 2
    in test2 2
    in test1 2

So you see it's either test1's RequestFactory point to itself, or test2's RequestFactory point to itself. PySonar happens to run test2.py first, so test1's RequestFactory points to itself.

There is not much use trying examples like this. They are ill-intended confusing programs.
